theme: jekyll-theme-minimal
title: Manuel Banz
description: <b>web, sociology and politics</b><br/>current and older projects and scientific papers<br/><br/><a href="https://www.xing.com/profile/Manuel_Banz2">XING</a><br/><a href="https://www.linkedin.com/in/manuel-banz-698070181/">LinkedIn</a><br/><a href="https://twitter.com/89Berlin">Twitter</a>
